openapi: 3.0.0
info:
  title: RAG Chatbot Backend API
  version: 1.0.0
  description: Backend API for the RAG Chatbot system with sitemap ingestion capabilities
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /:
    get:
      summary: Root endpoint
      description: Verify that the API is running
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "RAG Chatbot Backend API is running"

  /health:
    get:
      summary: Health check
      description: Perform a basic health check
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

  /api/v1/health:
    get:
      summary: API health check
      description: Perform an API-specific health check
      responses:
        '200':
          description: API health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  service:
                    type: string
                    example: "backend"

  /api/v1/ingest/sitemap:
    post:
      summary: Ingest a sitemap
      description: Process a sitemap URL and extract all URLs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sitemap_url
              properties:
                sitemap_url:
                  type: string
                  description: URL of the sitemap to ingest
                  example: "https://example.com/sitemap.xml"
      responses:
        '200':
          description: Sitemap ingestion result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResult'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500':
          description: Processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

  /api/v1/ingest/sitemap-index:
    post:
      summary: Ingest a sitemap index
      description: Process a sitemap index URL and extract all URLs from all referenced sitemaps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sitemap_url
              properties:
                sitemap_url:
                  type: string
                  description: URL of the sitemap index to ingest
                  example: "https://example.com/sitemap_index.xml"
      responses:
        '200':
          description: Sitemap index ingestion result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResult'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500':
          description: Processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

components:
  schemas:
    IngestionResult:
      type: object
      properties:
        sitemap_url:
          type: string
          description: The source sitemap URL
        urls_found:
          type: integer
          description: Number of URLs extracted
        urls:
          type: array
          items:
            type: string
          description: List of extracted URLs
        status:
          type: string
          description: Processing status
          enum: [success, error]
      required:
        - sitemap_url
        - urls_found
        - urls
        - status

    ErrorResult:
      type: object
      properties:
        error:
          type: string
          description: Error message
        status_code:
          type: integer
          description: HTTP status code
      required:
        - error
        - status_code